name: Build WebView App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configuration de Xcode
        run: xcode-select -p

      - name: Build de l'application pour iPhone (Arm64)
        run: |
          # On build pour le SDK iphoneos (vrais appareils) et non simulateur
          xcodebuild -project MyWebViewApp.xcodeproj \
                     -scheme MyWebViewApp \
                     -sdk iphoneos \
                     -configuration Release \
                     IPHONEOS_DEPLOYMENT_TARGET=12.0 \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     clean build \
                     CONFIGURATION_BUILD_DIR=$PWD/build

      - name: Creation du fichier IPA
        run: |
          cd build
          # Un IPA est juste un zip contenant un dossier nomm√© Payload
          mkdir Payload
          cp -r MyWebViewApp.app Payload/
          zip -r ../ElQabila.ipa Payload

      - name: Telechargement de l'IPA final
        uses: actions/upload-artifact@v4
        with:
          name: ElQabila-iPhone-Installation
          path: ElQabila.ipa
